### ISSUE TITLE
Issue on multi requests

### ISSUE THREAD

**Issue by aignacio** [RoaLogic/ahb3lite_apb_bridge#2]
Hi,
I'm using the IP to integrate some APB peripherals in my bus but it seems to be not managing to answer correctly when a sequence of two requests appears spaced by one clock cycle. What happens in the end is that the first request it's corrected routed to the bus but the last one doesn't as showed in the image below. The requests are simple with no burst (NONSEQ_HTRANS) and the slave it's inside the mask range as mentioned in the datasheet.
![error](https://user-images.githubusercontent.com/5991372/61992917-f54a0d80-b064-11e9-8989-930df71199ad.png)
If the requests are spaced by more than 5 clock cycles, then I can request again with no problems but if a new request arrives in the following next 2 clock cycles it happens again.
![Screenshot from 2019-07-27 11-54-51](https://user-images.githubusercontent.com/5991372/61992965-8620e900-b065-11e9-8a47-af7df87ba963.png)
Top file with the modules are in the zip below...
[sim.zip](https://github.com/RoaLogic/ahb3lite_apb_bridge/files/3438035/sim.zip)

**Comment by rherveille** [comment]
HREADYOUT should remain ‘0’ until the transfer completes. In your waveform it remains ‘0’ for only 1 cycle.

Can you show the HREADYOUT port from the bridge?

 

Thanks,

Richard

 

 

Richard Herveille

Managing Director

Phone +31 (45) 405 5681

Cell +31 (6) 5207 2230

richard.herveille@roalogic.com

 

 

 

On 27/07/2019, 11:58, "Ânderson Ignacio da Silva" <notifications@github.com> wrote:

 

Hi,
I'm using the IP to integrate some APB peripherals in my bus but it seems to be not managing to answer correctly when a sequence of two requests appears spaced by one clock cycle. What happens in the end is that the first request it's corrected routed to the bus but the last one doesn't as showed in the image below. The requests are simple with no burst (NONSEQ_HTRANS) and the slave it's inside the mask range as mentioned in the datasheet.

If the requests are spaced by more than 5 clock cycles, then I can request again with no problems but if a new request arrives in the following next 2 clock cycles it happens again.

Top file with the modules are in the zip below...
sim.zip

**Comment by aignacio** [comment]
Hi @rherveille,
thanks for the answer, the **HREADYOUT** from the bridge it's the blue signal in the image  below. According to this signal makes sense it switches just after some clock cycles, but what I'm worried about is that this **HREADYOUT** from the bridge connects to the **slave HREADY [2]** and the interconnect seems to not be routing it right....the interconnect is the [ahb3lite_interconnect](https://github.com/RoaLogic/ahb3lite_interconnect)

![Screenshot from 2019-07-27 16-33-23](https://user-images.githubusercontent.com/5991372/61995712-4b7e7700-b08c-11e9-9613-9dca54b38fa2.png)

My scenario is the following:
![RISCorVo SoC (1)](https://user-images.githubusercontent.com/5991372/61996335-76b89480-b093-11e9-84e5-977d675fa94f.jpg)

**Comment by rherveille** [comment]
Hi,

 

You’re using the exact same configuration as we typically use.

Since we’ve used this many times we know it works.

 

Now connecting HREADYOUT and HREADY is tricky.

Please make sure that HREADYOUT and HREADY is connected correctly on all master/slave ports.

 

Richard

 

 

 

Richard Herveille

Managing Director

Phone +31 (45) 405 5681

Cell +31 (6) 5207 2230

richard.herveille@roalogic.com

 

 

 

On 27/07/2019, 16:56, "Ânderson Ignacio da Silva" <notifications@github.com> wrote:

 

Hi @rherveille,
thanks for the answer, the HREADYOUT from the bridge it's the blue signal in the image below. According to this signal makes sense it switches just after some clock cycles, but what I'm worried about is that this HREADYOUT from the bridge connects to the slave HREADY [2] and the interconnect seems to not be routing it right....the interconnect is the ahb3lite_interconnect

My scenario is the following:

**Comment by aignacio** [comment]
Hi @rherveille ,
I'm following the same scheme used in the testbench provided with the IP
![Screenshot from 2019-07-27 20-49-08](https://user-images.githubusercontent.com/5991372/61998421-0ff5a400-b0b0-11e9-9b89-e904e5f65825.png)
So, once I run the simulation and expand the signals, it's possible to see that master[1] receives the hready out from the slave bridge, but even though does not hold the hreadyout input in the master side.
![Screenshot from 2019-07-27 20-50-10](https://user-images.githubusercontent.com/5991372/61998427-27cd2800-b0b0-11e9-9f8b-88b687b68c15.png)
AFAIU by your documentation, the **hreadyout** output from the ahb interconnect it's a signal that indicates that the last transaction with the slaves connected (and that had granted the access) finished. So, am I making some mistake in the AHB master transaction due the way that I handle the signals? My flow to start a transaction it's assert HSEL in the address phase and then in the next cc, de-assert it. Also the HREADY signal from my master is always asserted, is this some wrong?

Ps.: I'm using master.HREADYOUT from the interconnect to understand that the last transaction it's still being issued...

**Comment by aignacio** [comment]
Hi @rherveille,
I solved the problem connecting the **HREADY** **output** of my master with the **HREADYOUT** **input** from the interconnect (on my master side). I didn't know that the master should mimetize the state of the slaves through this signals. Now my issue is with PSTRB from AHB to APB converter being always zero what makes the peripheral not write to the correspondent registers.

![sdfsf](https://user-images.githubusercontent.com/5991372/62113271-924eb580-b2b4-11e9-9573-41d703c51ec2.jpeg)

**Comment by aignacio** [comment]
@rherveille 
here is simulation and the code snippet of **pstrb** generation signal, what seem weird is that the signals used inside the function are set **after** the fsm change the state not before that as it should be...

![Screenshot from 2019-07-30 11-47-18](https://user-images.githubusercontent.com/5991372/62119511-0cd10280-b2c0-11e9-8e91-9a8d1d6c727c.png)

![Screenshot from 2019-07-30 11-47-22](https://user-images.githubusercontent.com/5991372/62119516-0fcbf300-b2c0-11e9-81db-d1819cc90d6c.png)

Could you clarify why this happens? tks

**Comment by aignacio** [comment]
Fixed on https://github.com/RoaLogic/ahb3lite_apb_bridge/commit/62e86006f4ffb3cdb29f3f4d5da81bbe0e7c31cc, thanks!
